Slicer/SlicerExecutionModel

CTestConfig.cmake

This commit adds CTestConfig.cmake file that will tell ctest
where to submit its results.
Results will be posted here:
http://slicer.cdash.org/index.php?project=SlicerExecutionModel

ENH: Support submission of test results on CDash

---

test/Docker-ITK-v4.8.0_USE_SYSTEM_LIBRARIES-OFF/Dockerfile
test/Docker-ITK-v4.8.0_USE_SYSTEM_LIBRARIES-OFF/build.sh
test/Docker-ITK-v4.8.0_USE_SYSTEM_LIBRARIES-OFF/run.sh
test/Docker/Dockerfile
test/Docker/build.sh
test/Docker/run.sh
test/Docker/test.sh

This commit add a Docker file allowing to easily build
and test the project. It contains the recipe allowing to
build ITK so that SlicerExecutionModel can quickly be
configured, built and tested.
This PR reorganize part of #46 to only include docker changes

ENH: Add Docker Test file

---

README.md
circle.yml

This commit add files to perform continuous integration testing
using the Docker container set up in PR #49.
It contains the recipe to perform tests using circleCI and provides
the result in the README section.
This PR reorganize part of #46 to only include circleCI changes

ENH: Add circleCI files

---

ModuleDescriptionParser/CMakeLists.txt

Previous transitive contamination of the library
linkage would cause nearly all libraries to depend
on each other.  As we fix this in ITK proper (work
by Zach Williamson), we need to set the COMPONENTS
to include the items that we use.
In this example, we need ITKExpat library functions,
so including ITKIOExpat no longer transatively includes
ITKExpat (third party) publicly to child projects.  This
means that it must be included directly. NOTE, Had we used
only ITKIOExpat functions, this would not be necessary.

COMP: Add missing link dependancy for ITKExpat

---

circle.yml
test/Docker/run.sh
test/Docker/test.sh

This commit enables continuous integration testing with docker to
submit results on the dashboard with a more relevant build name.
This build name corresponds to the docker image tag that was previously
set up in PR #49 to specify the build option used by the image.
This commit has been tagged as WIP because the process has only been
tested using the Docker script run.sh. When making the PR, the circleCI
process will be automatically tested.

ENH: Add Relevant BUILDNAME for CDash submission

---

CMake/SEMMacroBuildCLI.cmake

Unparsed arguments are saved in <prefix>_UNPARSED_ARGUMENTS [1]. In this case, <prefix> is LOCAL_SEM, so the variable containing the unparsed arguments is called LOCAL_SEM_UNPARSED_ARGUMENTS.
[1] https://cmake.org/cmake/help/v3.0/module/CMakeParseArguments.html

BUG: Wrong unparsed arguments variable name

---

CMake/SEMMacroBuildCLI.cmake
GenerateCLP/GenerateCLP.cxx

For non-Windows builds, use hidden visibiltity on the CLI library when built
as a shared library and when the compiler supports it. This decreases disk
usage and improves load time of the CLI.
On a 3D Slicer MinSizeRel Linux build this:
- Reduces the `lib/Slicer-4.5/cli-modules` directory from 104MB to 89MB
- Reduces Slicer startup time from 20.2sec to 16.2sec

ENH: Use hidden visibility on the CLI library.

---

CMake/SEMMacroBuildCLI.cmake

To address:
[ 66%] Linking CXX shared library
/scratch/johnsonhj/src/BT-11/lib/libPerformMetricTestLib.dylib
ld: warning: direct access in _ModuleEntryPoint to global weak symbol typeinfo
for itk::BSplineTransform means the weak symbol cannot be overridden at
runtime. This was likely caused by different translation units being compiled
with different visibility settings.
ld: warning: direct access in itk::BSplineTransform::New() to global weak
symbol typeinfo for itk::BSplineTransform means the weak symbol cannot be
overridden at runtime. This was likely caused by different translation units
being compiled with different visibility settings.
ld: warning: direct access in itk::BSplineTransform::New() to global weak
symbol typeinfo name for itk::BSplineTransform means the weak symbol cannot …

COMP: Do not use hidden visibility when ITK is built statically.

---

GenerateCLP/GenerateCLP.cxx
GenerateCLP/GenerateCLP.h

Fixes `conversion from 'size_t' to 'int', possible loss of data` warning.

Made implicit conversion explicit (size_t to int).

---

GenerateCLP/UseGenerateCLP.cmake.in

The find_package(ITK ...) with limited components caused
this second call to find_package(ITK) within GenerateCLP to
clobber the find_package(ITK) that an end user may have
called previously.  This would cause problems because
the end-user application now would only have access to the
limited set of modules that GenerateCLP needed.

BUG: find_package(ITK ...) clobbered existing

---

ModuleDescriptionParser/CMakeLists.txt
ModuleDescriptionParser/ModuleDescription.cxx
ModuleDescriptionParser/ModuleDescriptionParserConfigure.h.in

Following commit 65a39fb (STYLE: Remove obsolete ModuleFactory class), settings
the option ModuleDescriptionParser_USE_PYTHON has no effect. This commit
cleanup the build system to remove unneeded use of Python libraries.
In case developer are still the option ModuleDescriptionParser_USE_PYTHON,
an author warning will be reported.

STYLE: CMakeLists: Remove obsolete option ModuleDescriptionParser_USE_PYTHON

---

ModuleDescriptionParser/CMakeLists.txt

Initially introduced in Slicer r6773 (ENH: Slicer3 Spring Installation
Clean Up), finding and linking against pthread library is not needed.

STYLE: CMakeLists: Finding of threading library is not needed anymore

---

CMake/FindJsonCpp.cmake
GenerateCLP/CMakeLists.txt
SlicerExecutionModelConfig.cmake.in

There are a few items here to improve the JsonCpp support for
SlicerExecutionModel:
- FindJsonCpp.cmake:
Add /src/lib_json directory to the list of directories searches for the
json library. This is the default build directory for the jsoncpp library.
- GenerateCLP/CMakeLists.txt:
Add missing include_directory and missing library linkage to JsonCpp.
- SlicerExecutionModelConfig.cmake.in:
Add missing checks for JsonCpp. Also add definition for windows compilation
@jcfr: Would you mind taking a look ?

ENH: Improve JsonCpp support for SlicerExecutionModel

---

GenerateCLP/CMakeLists.txt

This improves on the work done in PR #73.
Specifically this adds the JsonCpp dll in the path of the GenerateCLP launcher.

ENH: Add JsonCpp path to the GenerateCLP launcher

---

GenerateCLP/GenerateCLP.cxx
GenerateCLP/Testing/CLPExample1/CLPExample1.cxx
GenerateCLP/Testing/CLPExample1/CLPExample1.xml

The parsing was including the file from the JSON file even if the array
was empty. To remediate to this, we test for the array size to make
sure it's not empty before adding the flag and the following values.
Testing is improved as well by adding an argument with the "multiple" flag
and making sure it's serialized/deserialized correctly (it should always
be empty).

ENH: Improve support for empty arrays

---

GenerateCLP/GenerateCLP.cxx
GenerateCLP/Testing/CLPExample1/CMakeLists.txt
GenerateCLP/Testing/CLPTestMultiple/CLPTestMultiple.cxx
GenerateCLP/Testing/CLPTestMultiple/CLPTestMultiple.xml
GenerateCLP/Testing/CLPTestMultiple/CMakeLists.txt
GenerateCLP/Testing/CMake/GenerateCLPTestMacros.cmake
GenerateCLP/Testing/CMakeLists.txt
GenerateCLP/Testing/PointExample1/PointExample1.xml

Following the concerns raised in the Slicer's #576 (https://github.com/Slicer/Slicer/pull/576), this addresses:
- Multiple argument bug
- Quote escaping issue
This also adds more testing and factorizes some of the testing infrastructure to be more easily extendable.
@jcfr, @thewtex: PTAL

Fix deserialization multiple args

---

ModuleDescriptionParser/JsonSerializationUtilities.h

This commit removes method ReadJsonParameter that became obsolete
after ba54510 (ENH: Allow CLI to deserialize without the required arguments)
It will fix warning like this one:
```
/path/to/SlicerExecutionModel/ModuleDescriptionParser/JsonSerializationUtilities.h:43:6: warning: ‘void {anonymous}::ReadJsonParameter(const Json::Value&, std::__cxx11::string&)’ defined but not used [-Wunused-function]
void ReadJsonParameter( const Json::Value & parameter, std::string & value )
^
```

JsonSerializationUtilities: Remove unused method

---

GenerateCLP/CMakeLists.txt
GenerateCLP/GenerateCLPConfig.cmake.in
GenerateCLP/Testing/CMake/GenerateCLPTestPrerequisites.cmake.in
SlicerExecutionModelConfig.cmake.in

VTK does not use JsonCpp_DIR. In an effort to be consistent across
projects, we should only refer to JsonCpp_INCLUDE_DIR and JsonCpp_LIBRARY.
This is futhermore reinforce that JsonCPP_DIR does NOT have to be defined
for GenerateCLP to work.
cc: @jcfr

ENH: Uniformize the use of JsonCpp with VTK

---

GenerateCLP/CMakeLists.txt

The GenerateCLP_FORWARD_PATHS_BUILD and GenerateCLP_FORWARD_PATHS_INSTALL
variables are used to generate a C++ macro. In d58e6643f5c12f568da5861ba133ac3c4b4e05cb
a bug was introduced when SlicerExecutionModel is built without JSON
support, the macro is generated with an empty line, breaking compilation.
This commit fixes the GenerateCLP_FORWARD_PATHS_[BUILD/INSTALL] variables
to make sure the C++ macro are always valid.
See Issue #81

BUG: Fix GenerateCLP_FORWARD_PATHS_[BUILD/INSTALL] variable

---

GenerateCLP/GenerateCLP.cxx

bool isPresent = dvOptionnalArgsIt != deserializedVectorFlaggedArgs.end(); \
conflicted with
bool isPresent = dvMultipleArgsIt != deserializedMultipleArgsMap.end(); \
The isPresent variables have now been renamed to avoid that hidden local vars.

WARN: Rename isPresent variables to avoid hidden local variable

---

ModuleDescriptionParser/ModuleDescription.cxx

SlicerExecutionModel/ModuleDescriptionParser/ModuleDescription.cxx:595:
warning: declaration shadows a field of 'ModuleDescription' [-Wshadow]
SetTargetCallback(void* LibraryLoader, TargetCallbackType
targetCallback)
SlicerExecutionModel/ModuleDescriptionParser/ModuleDescription.h:175:
note: previous declaration is here
void* LibraryLoader;
Changed function parameter to use lower case libraryLoader as is done
for other parameter passed to that function that also has a parallel
member variable

BUG: ModuleDescription: Param LibraryLoader shadows this->LibraryLoader

---

GenerateCLP/GenerateCLP.cxx

```
/path/to/SlicerExecutionModel/GenerateCLP/GenerateCLP.cxx:678:27: warning: unused variable 'cppType' [-Wunused-variable]
const std::string & cppType = paramIt->GetCPPType();
^
```

COMP: GenerateCLP: Fix -Wunused-variable warning

---

GenerateCLP/GenerateCLP.cxx
ModuleDescriptionParser/BatchMakeUtilities.cxx
ModuleDescriptionParser/ModuleDescription.cxx
ModuleDescriptionParser/ModuleDescription.h
ModuleDescriptionParser/ModuleDescriptionParser.cxx
ModuleDescriptionParser/ModuleParameter.cxx
ModuleDescriptionParser/ModuleParameter.h
ModuleDescriptionParser/Testing/ModuleDescriptionTest.cxx
ModuleDescriptionParser/itkSEMModuleParameterSerializer.cxx
ModuleDescriptionParser/itkSEMModuleParameterSerializer.h

This attribute (declared in [moduleParameter](https://github.com/Slicer/SlicerExecutionModel/compare/master...jbvimort:defaultValueNamingImprovement?expand=1#diff-2c64a747d4f10af24e65281fb99947d0L372) ) is first used to store the default value specified in the xml file, but it is then used to store the value specified by the user through the user interface or the result computed by the CLI.
Renaming the attribute from 'default' to 'value' as well as all the get/set functions related seems to make more sense.
Some modifications will also be necessary in Slicer, particularly in the part managing the CLIs (like [here](https://github.com/Slicer/Slicer/blob/9e7de7256691782a2650a312313d47aafa31c4a2/Libs/MRML/CLI/vtkMRMLCommandLineModuleNode.cxx#L290) for example).
For the different extensions …

STYLE: Renaming of the 'defaultValue' parameter's attribute to 'Value'

---

CMake/SEMMacroBuildCLI.cmake

Previously, each CLI needed to have a cxx file called the same as the given executable name. This was restricting the possibility to name an executable differently based, for example, on configuration or compilation options. This patch introduced a new option to disable this requirement. This allows SEMMacroBuildCLI to stay backward compatible while allowing more flexibiliy in the naming of the cxx files and the executable [1].
[1] https://docs.google.com/a/kitware.com/document/d/1Wkl7RFVb87ZbcgZnSQ4nmyM2bFEQUN1xT-Q5ALLJh8w/edit?usp=sharing

ENH: cxx and executable can have different names.

---

test/Docker/Makefile

Since BUILD_DATE is always different, the image is already ensured
to be different. This comment is done to have consistent makefile and
follow the best practice.

Makefile: Ensure image is deleted if different

---

CMake/SEMMacroBuildCLI.cmake

Interprocedural optimization, aka link time optimization (LTO), is the
required for newer optimization techniques on modern compilers.
Due to backwards compatibility concerns, it is not enabled by default in
CMake.
Enable the required flags on SEM targets.
CMake version 3.13.0 is required for Visual Studio support.

SEMMacroBuildCLI: Enable interprocedural optimization on targets

---

ModuleDescriptionParser/ModuleDescriptionParser.cxx

QStrings are used for Help and Acknowledgement frame on Slicer module
panel. Newline characters are not respected by QString. They need to be
line breaks.
Fixes issue #9 on the SlicerExecutionModel issue tracker.
Fixes issue 2781 on Slicer bug tracker.

Newline characters replaced by line breaks (rebased)

---

ModuleDescriptionParser/CMakeLists.txt

CMake Deprecation Warning at
share/cmake/Modules/GenerateExportHeader.cmake:414 (message):
The add_compiler_export_flags function is obsolete.  Use the
CXX_VISIBILITY_PRESET and VISIBILITY_INLINES_HIDDEN target properties
instead.
Call Stack (most recent call first):
ModuleDescriptionParser/CMakeLists.txt:154 (add_compiler_export_flags)
Resolves #102

COMP: Replace obsolete add_compiler_export_flags

---

ModuleDescriptionParser/ModuleDescriptionParser.cxx
ModuleDescriptionParser/ModuleParameter.cxx
ModuleDescriptionParser/ModuleParameter.h

It was possible to define references before, but they have special meaning (set parent transform, etc), and they are defined "in reverse", i.e. in the referenced object.
This change adds support for generic, forward references, which allow specifying any type of reference between two nodes. For example in a registration module, the output transform can specify node references to the moving and fixed images.
An example element (under a parameter element) is:
```
<reference role="spatialRegistrationMoving" parameter="movingVolume"/>
```

ENH: Add forward reference support

---

ModuleDescriptionParser/ModuleParameter.h

SlicerExecutionModel/ModuleDescriptionParser/ModuleParameter.h:97:11: warning:
'const' type qualifier on return type has no effect [-Wignored-qualifiers]
virtual const void GetForwardReferences(
^~~~~~
1 warning generated.

COMP: Fix compilation warning

---

tclap/include/tclap/ValuesConstraint.h

Both SlicerExecutionModel and DCMTK find and define
define HAVE_SSTREAM variable.    Protect the definition
of HAVE_SSTREAM when it is already defined.

COMP: Protect from redefinition warnings

---

ModuleDescriptionParser/CMakeLists.txt
ModuleDescriptionParser/ModuleDescriptionParserPragmas.h.in

Since the same compiler is used to compile both the components of this project
and the "client" project, this is a non issue.
See https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4251?view=vs-2019

COMP: Fix VC++ C4251 warnings: needs to have dll-interface to be used by clients

---

ModuleDescriptionParser/ModuleDescription.xsd
ModuleDescriptionParser/ModuleDescriptionParser.cxx

This allows specifying that point list should be interpreted as line, angle, curve, or closed curve.
xsd file does not constrain the type (the same way as for image, geometry, etc.).

Add optional "type" attribute to "pointfile" element

---

test/Docker-ITK-master_USE_SYSTEM_LIBRARIES-OFF/Dockerfile
test/Docker-ITK-v4.10.1_USE_SYSTEM_LIBRARIES-OFF/Dockerfile
test/Docker-ITK-v4.13.0_USE_SYSTEM_LIBRARIES-OFF/Dockerfile
test/Docker-ITK-v4.8.0_USE_SYSTEM_LIBRARIES-OFF/Dockerfile

A newer cmake version is necessary for building
SlicerExecutionModel. These images are needed
for CI to pass.

ENH: Update docker base image to include newer cmake version.

---

ModuleDescriptionParser/CMakeLists.txt

find_package(ParameterSerializer) may do a find_package(ITK) that may
changes ITK_LIBRARIES used to target_link_libraries.
See https://github.com/InsightSoftwareConsortium/ITK/issues/1892

COMP: Do not link ModuleDescriptionParser with entire ITK

---

GenerateCLP/GenerateCLPConfig.cmake.in
SlicerExecutionModelConfig.cmake.in

This commit ensures project expected to find JsonCpp after finding
SlicerExecutionModel can do successfully even when SlicerExecutionModel
is built without ParameterSerializer support.
See https://github.com/Slicer/Slicer/issues/5080

COMP: Do not force JsonCpp and ParameterSerializer DIR variable to empty string
